const User = require("./User");

let admin = User.newAdmin("caleb", "felix")
let user1 = admin.newUser("u1", "u1")
let user2 = admin.newUser("u2", "u2")

console.log(admin)
console.log(user2)
console.log(admin.getAllUsers())
console.log(admin.updateUser(2, "FirstName", "Updated"))
console.log(user1.createContact("caleb2", "felix2"))
console.log(user1.createContact("del", "del"))
console.log(admin.createContact("caleb2", "felix2"))
console.log(admin.getAllContacts())
console.log(user1.getAllContacts())
console.log(user1.updateContact(1,"lastName", "updated contact"))
console.log(user1.getAllContacts())
console.log(admin.deleteUser(2))
user1.createContactDetail(0,"email","del@mail.com")
user1.createContactDetail(0,"number","839293993")

console.log(user1.createContactDetail(1,"home","839293993"))
console.log(user1.getContactDetails(1))
console.log(user1.updateContactDetails(0, 1, "work-Email", "work@mail.com"))
console.log(user1.deleteContactDetails(0, 1))